# This is the SAM template that represents the architecture of your serverless application
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-template-basics.html

# The AWSTemplateFormatVersion identifies the capabilities of the template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/format-version-structure.html
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  CW Lambda Application managed by SAM

# Transform section specifies one or more macros that AWS CloudFormation uses to process your template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/transform-section-structure.html
Transform:
- AWS::Serverless-2016-10-31

# Resources declares the AWS resources that you want to include in the stack
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html
Resources:
  ImageResizerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/image-resizer.imageResizerHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      MemorySize: 1024
      Timeout: 10
      Description: A Lambda function that resizes images.
      Environment:
        Variables:
          REGION: "{{resolve:ssm:/captain-resize/aws-region}}"
          ORIGINAL_BUCKET: "{{resolve:ssm:/captain-resize/original-bucket}}"
          DESTINATION_BUCKET: "{{resolve:ssm:/captain-resize/destination-bucket}}"
          ALLOWED_SIZES: "{{resolve:ssm:/captain-resize/allowed-sizes}}"
          ALLOWED_EXTENSIONS: "{{resolve:ssm:/captain-resize/allowed-extensions}}"
      Policies:
        - AWSLambdaBasicExecutionRole
        - S3ReadPolicy:
            BucketName: "{{resolve:ssm:/captain-resize/original-bucket}}"
        - S3WritePolicy:
            BucketName: "{{resolve:ssm:/captain-resize/destination-bucket}}"
      AutoPublishAlias: live
      FunctionUrlConfig:
        AuthType: NONE

  ContactFormFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/contact-form.contactFormHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      MemorySize: 1024
      Timeout: 10
      Description: A Lambda function for contact form.
      Environment:
        Variables:
          REGION: "{{resolve:ssm:/contact-form/aws-region}}"
          SNS_TOPIC: "{{resolve:ssm:/contact-form/sns-topic}}"
      Policies:
        - AWSLambdaBasicExecutionRole
        - SNSPublishMessagePolicy:
            TopicName: "{{resolve:ssm:/contact-form/sns-topic-name}}"
      AutoPublishAlias: live
      FunctionUrlConfig:
        AuthType: NONE
        Cors:
          AllowOrigins:
            - "*"

Outputs:
  ImageResizerFunctionEndpoint:
    Description: Image Resizer Function URL Endpoint.
    Value: !GetAtt ImageResizerFunctionUrl.FunctionUrl
  ContactFormFunctionEndpoint:
    Description: Image Resizer Function URL Endpoint.
    Value: !GetAtt ContactFormFunctionUrl.FunctionUrl
